# Generated by Django 3.1.7 on 2021-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="search_result",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
